spring:
  application:
    name: "talentSuite"

  datasource:
    url: jdbc:mysql://localhost:3306/talentSuite
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
